package com.epitech.dashboard.WeatherTime;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class WeatherTimeLayout extends AbsoluteLayout {
    protected VerticalLayout verticalLayout;
    protected Label city;
    protected Image image;
    protected Label temperature;
    protected Label wind;
    protected Label clock;

    public WeatherTimeLayout() {
        Design.read(this);
    }
}
