package com.epitech.dashboard.Quote;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class QuoteDataLayout extends AbsoluteLayout {
    protected VerticalLayout verticalLayout;
    protected Label symbol;
    protected Label vide;
    protected Label companyName = null;
    protected Label open = null;
    protected Label close = null;
    protected Label high = null;
    protected Label low = null;
    protected Label latestTime = null;
    protected Label latestVolume = null;

    public QuoteDataLayout() {
        Design.read(this);
    }
}
